const products = [
    // Apple
    {
      id: 1,
      name: "iPhone 15 Pro Max",
      price: 29990000,
      discount: 10,
      rating: 4.8,
      brand: "Apple",
      image: "src/product_images/iphone15promax.webp",
      description: "Điện thoại cao cấp với chip A17 Pro, camera tiên tiến và thiết kế titan.",
      stock: 10,
      sales: 5000,
      views: 200000,
      specs: {
        screen: "6.7 inch OLED, 120Hz",
        chipset: "Apple A17 Pro",
        ram: "8GB",
        camera: "48MP + 12MP + 12MP",
        battery: "4441mAh, sạc nhanh 20W",
        os: "iOS 17",
      },
    },
    {
      id: 2,
      name: "iPhone 15",
      price: 22990000,
      discount: 5,
      rating: 4.6,
      brand: "Apple",
      image: "src/product_images/iphone15.webp",
      description: "Sản phẩm mới nhất của Apple với thiết kế đột phá và hiệu năng mạnh mẽ.",
      stock: 15,
      sales: 4000,
      views: 180000,
      specs: {
        screen: "6.1 inch OLED, 60Hz",
        chipset: "Apple A16 Bionic",
        ram: "6GB",
        camera: "48MP + 12MP",
        battery: "3877mAh, sạc nhanh 20W",
        os: "iOS 17",
      },
    },
    {
      id: 3,
      name: "iPhone 14 Pro Max",
      price: 25990000,
      discount: 7,
      rating: 4.7,
      brand: "Apple",
      image: "src/product_images/iphone14promax.webp",
      description: "Một trong những flagship bán chạy nhất của Apple với Dynamic Island.",
      stock: 8,
      sales: 3500,
      views: 150000,
      specs: {
        screen: "6.7 inch OLED, 120Hz",
        chipset: "Apple A16 Bionic",
        ram: "6GB",
        camera: "48MP + 12MP + 12MP",
        battery: "4323mAh, sạc nhanh 20W",
        os: "iOS 16",
      },
    },
    // Samsung
    {
      id: 4,
      name: "Samsung Galaxy S24 Ultra",
      price: 26990000,
      discount: 5,
      rating: 4.7,
      brand: "Samsung",
      image: "src/product_images/galaxys24ultra.webp",
      description: "Flagship với bút S-Pen và camera 200MP cho trải nghiệm chụp ảnh tuyệt vời.",
      stock: 12,
      sales: 5500,
      views: 250000,
      specs: {
        screen: "6.8 inch Dynamic AMOLED 2X, 120Hz",
        chipset: "Snapdragon 8 Gen 3",
        ram: "12GB",
        camera: "200MP + 10MP + 12MP + 50MP",
        battery: "5000mAh, sạc nhanh 45W",
        os: "Android 14",
      },
    },
    {
      id: 5,
      name: "Samsung Galaxy S23 Ultra",
      price: 24990000,
      discount: 8,
      rating: 4.6,
      brand: "Samsung",
      image: "src/product_images/galaxys23ultra.webp",
      description: "Siêu phẩm với thiết kế cao cấp, màn hình cong và camera độ phân giải cao.",
      stock: 10,
      sales: 4800,
      views: 220000,
      specs: {
        screen: "6.8 inch Dynamic AMOLED 2X, 120Hz",
        chipset: "Snapdragon 8 Gen 2",
        ram: "12GB",
        camera: "200MP + 10MP + 12MP + 50MP",
        battery: "5000mAh, sạc nhanh 45W",
        os: "Android 13",
      },
    },
    // Xiaomi
    {
      id: 6,
      name: "Xiaomi 14 Pro",
      price: 18990000,
      discount: 7,
      rating: 4.5,
      brand: "Xiaomi",
      image: "src/product_images/xiaomi14pro.webp",
      description: "Điện thoại flagship với màn hình OLED cong và camera Leica.",
      stock: 14,
      sales: 6000,
      views: 230000,
      specs: {
        screen: "6.73 inch OLED, 120Hz",
        chipset: "Snapdragon 8 Gen 3",
        ram: "12GB",
        camera: "50MP + 50MP + 50MP",
        battery: "4880mAh, sạc nhanh 120W",
        os: "Android 14",
      },
    },
    {
      id: 7,
      name: "Xiaomi Redmi Note 12 Pro",
      price: 8990000,
      discount: 5,
      rating: 4.4,
      brand: "Redmi",
      image: "src/product_images/redminote12pro.webp",
      description: "Smartphone giá rẻ với camera 200MP, màn hình AMOLED.",
      stock: 20,
      sales: 7500,
      views: 270000,
      specs: {
        screen: "6.67 inch AMOLED, 120Hz",
        chipset: "Dimensity 1080",
        ram: "8GB",
        camera: "200MP + 8MP + 2MP",
        battery: "5000mAh, sạc nhanh 67W",
        os: "Android 13",
      },
    },
    // Oppo
    {
      id: 8,
      name: "Oppo Find X6 Pro",
      price: 20990000,
      discount: 6,
      rating: 4.5,
      brand: "Oppo",
      image: "src/product_images/oppofindx6pro.webp",
      description: "Điện thoại flagship với hệ thống camera Hasselblad chuyên nghiệp.",
      stock: 10,
      sales: 4000,
      views: 150000,
      specs: {
        screen: "6.82 inch AMOLED, 120Hz",
        chipset: "Snapdragon 8 Gen 2",
        ram: "12GB",
        camera: "50MP + 50MP + 50MP",
        battery: "5000mAh, sạc nhanh 100W",
        os: "Android 13",
      },
    },
    // Các sản phẩm khác...
    {
        id: 9,
        name: "iPhone 13",
        price: 17990000,
        discount: 5,
        rating: 4.6,
        brand: "Apple",
        image: "src/product_images/iphone13.webp",
        description: "Điện thoại bền bỉ với chip A15 Bionic và camera chất lượng cao.",
        stock: 20,
        sales: 3200,
        views: 140000,
        specs: {
          screen: "6.1 inch OLED, 60Hz",
          chipset: "Apple A15 Bionic",
          ram: "4GB",
          camera: "12MP + 12MP",
          battery: "3240mAh, sạc nhanh 20W",
          os: "iOS 16",
        },
      },
      // Samsung
      {
        id: 10,
        name: "Samsung Galaxy A54",
        price: 9990000,
        discount: 7,
        rating: 4.5,
        brand: "Samsung",
        image: "src/product_images/galaxya54.webp",
        description: "Màn hình AMOLED, pin 5000mAh và camera chất lượng cao.",
        stock: 25,
        sales: 7000,
        views: 280000,
        specs: {
          screen: "6.4 inch Super AMOLED, 120Hz",
          chipset: "Exynos 1380",
          ram: "8GB",
          camera: "50MP + 12MP + 5MP",
          battery: "5000mAh, sạc nhanh 25W",
          os: "Android 14",
        },
      },
      // Xiaomi
      {
        id: 11,
        name: "Xiaomi 13 Ultra",
        price: 21990000,
        discount: 6,
        rating: 4.7,
        brand: "Xiaomi",
        image: "src/product_images/xiaomi13ultra.webp",
        description: "Camera Leica, Snapdragon 8 Gen 2 và màn hình cong 2K.",
        stock: 10,
        sales: 5000,
        views: 230000,
        specs: {
          screen: "6.73 inch AMOLED, 120Hz",
          chipset: "Snapdragon 8 Gen 2",
          ram: "12GB",
          camera: "50MP + 50MP + 50MP + 50MP",
          battery: "5000mAh, sạc nhanh 90W",
          os: "Android 13",
        },
      },
      // Vivo
      {
        id: 12,
        name: "Vivo X90 Pro+",
        price: 20990000,
        discount: 5,
        rating: 4.6,
        brand: "Vivo",
        image: "src/product_images/vivox90proplus.webp",
        description: "Camera Zeiss, màn hình OLED 120Hz và Snapdragon 8 Gen 2.",
        stock: 8,
        sales: 4500,
        views: 190000,
        specs: {
          screen: "6.78 inch AMOLED, 120Hz",
          chipset: "Snapdragon 8 Gen 2",
          ram: "12GB",
          camera: "50MP + 48MP + 50MP + 64MP",
          battery: "4700mAh, sạc nhanh 80W",
          os: "Android 13",
        },
      },
      {
        id: 13,
        name: "Vivo V29",
        price: 9990000,
        discount: 4,
        rating: 4.4,
        brand: "Vivo",
        image: "src/product_images/vivov29.webp",
        description: "Camera selfie 50MP, màn hình cong 120Hz và sạc nhanh 80W.",
        stock: 12,
        sales: 5500,
        views: 170000,
        specs: {
          screen: "6.78 inch AMOLED, 120Hz",
          chipset: "Snapdragon 778G",
          ram: "8GB",
          camera: "50MP + 8MP + 2MP",
          battery: "4600mAh, sạc nhanh 80W",
          os: "Android 13",
        },
      },
      // Realme
      {
        id: 14,
        name: "Realme GT Neo 5",
        price: 13990000,
        discount: 6,
        rating: 4.5,
        brand: "Realme",
        image: "src/product_images/realmegtneo5.webp",
        description: "Snapdragon 8+ Gen 1, màn hình AMOLED 144Hz và sạc siêu nhanh 150W.",
        stock: 15,
        sales: 6000,
        views: 210000,
        specs: {
          screen: "6.74 inch AMOLED, 144Hz",
          chipset: "Snapdragon 8+ Gen 1",
          ram: "12GB",
          camera: "50MP + 8MP + 2MP",
          battery: "5000mAh, sạc nhanh 150W",
          os: "Android 13",
        },
      },
      {
        id: 15,
        name: "Realme 11 Pro+",
        price: 9990000,
        discount: 5,
        rating: 4.3,
        brand: "Realme",
        image: "src/product_images/realme11proplus.webp",
        description: "Camera 200MP, màn hình cong 120Hz và pin 5000mAh.",
        stock: 18,
        sales: 5800,
        views: 190000,
        specs: {
          screen: "6.7 inch AMOLED, 120Hz",
          chipset: "Dimensity 7050",
          ram: "8GB",
          camera: "200MP + 8MP + 2MP",
          battery: "5000mAh, sạc nhanh 100W",
          os: "Android 13",
        },
      },
      // Huawei
      {
        id: 16,
        name: "Huawei P60 Pro",
        price: 21990000,
        discount: 5,
        rating: 4.6,
        brand: "Huawei",
        image: "src/product_images/huaweip60pro.webp",
        description: "Camera tele 200X, màn hình OLED 120Hz và Kirin 9000S.",
        stock: 6,
        sales: 4000,
        views: 160000,
        specs: {
          screen: "6.67 inch OLED, 120Hz",
          chipset: "Kirin 9000S",
          ram: "8GB",
          camera: "48MP + 13MP + 48MP",
          battery: "4815mAh, sạc nhanh 88W",
          os: "HarmonyOS 3.1",
        },
      },
      {
        id: 17,
        name: "Huawei Mate 50 Pro",
        price: 20990000,
        discount: 4,
        rating: 4.5,
        brand: "Huawei",
        image: "src/product_images/huaweimate50pro.webp",
        description: "Công nghệ camera XMAGE, màn hình OLED 120Hz và pin 4700mAh.",
        stock: 9,
        sales: 4200,
        views: 170000,
        specs: {
          screen: "6.74 inch OLED, 120Hz",
          chipset: "Snapdragon 8+ Gen 1",
          ram: "8GB",
          camera: "50MP + 64MP + 13MP",
          battery: "4700mAh, sạc nhanh 66W",
          os: "HarmonyOS 3.0",
        },
      },
      // Honor
      {
        id: 18,
        name: "Honor Magic 5 Pro",
        price: 19990000,
        discount: 6,
        rating: 4.6,
        brand: "Honor",
        image: "src/product_images/honormagic5pro.webp",
        description: "Snapdragon 8 Gen 2, màn hình LTPO OLED 120Hz và camera tele 50MP.",
        stock: 10,
        sales: 4500,
        views: 175000,
        specs: {
          screen: "6.81 inch LTPO OLED, 120Hz",
          chipset: "Snapdragon 8 Gen 2",
          ram: "12GB",
          camera: "50MP + 50MP + 50MP",
          battery: "5100mAh, sạc nhanh 66W",
          os: "Android 13",
        },
      },    
  ];
  
  export default products;
  